//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
namespace Test11.Models
{
    using System;
    using System.Collections.Generic;

    public enum houseKeeperInfo1
    {
        HouseKeeper_Id=0,
        HouseKeeper_Name=1,
        HouseKeeper_Status=2,
        Room_Id=3
    }
    public enum hStatus1
    {
        Doing=0,
        Waiting=1
    }
    public partial class housekeeperinfo
    {
        [Required]
        [StringLength(7, MinimumLength = 3)]
        public int hId { get; set; }
        public string hName { get; set; }
        public int hStatus { get; set; }
        public int rId { get; set; }
    }
}
